@host = {{$dotenv MOCK_HOST}}
@jsonContentType = content-type: application/json
@userEmail = {{$dotenv MOCK_USER_EMAIL}}
@userPassword = {{$dotenv MOCK_USER_PASSWORD}}
###

# @name register
POST {{host}}/auth/register

{
  "email": "{{userEmail}}",
  "password": "{{userPassword}}",
  "fullName": "tai_man_chan"
}
###


# @name login
POST {{host}}/auth/login

{
  "email": "{{userEmail}}",
  "password": "{{userPassword}}"
}

###
@authHeader = Authorization: Bearer {{login.response.body.accessToken}}


# @name me
GET {{host}}/users/me
{{authHeader}}
###


# @name create_audience_segment
POST {{host}}/audiences/segments/
{{authHeader}}

{
  "name": "demo_audience_segment",
  "isTesting": false,
  "filters": {
    "profileFilter": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "type": "group",
      "level": 1,
      "conjunction": "and",
      "rules": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "type": "rule",
          "field": "gender",
          "operator": "in",
          "value": ["Female"]
        },
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "type": "rule",
          "field": "nationality",
          "operator": "in",
          "value": ["HKC"]
        }
      ]
    },
    "extraFilter": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "type": "group",
      "level": 1,
      "conjunction": "and",
      "rules": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "type": "rule",
          "field": "card_organization",
          "operator": "in",
          "value": ["Lane Crawford Hong Kong"]
        },
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "type": "rule",
          "field": "mail_group",
          "operator": "in",
          "value": ["HK"]
        }
      ]
    },
    "behavioralFilter": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "type": "group",
      "level": 1,
      "conjunction": "and",
      "rules": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "type": "rule",
          "field": "first_transaction_date",
          "operator": "on_or_after",
          "value": "2021-11-01",
          "groupBy": "AllDepts_AllRegions"
        }
      ]
    }
  }
}

###


@audienceId = {{create_audience_segment.response.body.id}}

# @name get_audience_segment
GET {{host}}/audiences/segments/{{audienceId}}
{{authHeader}}
###


# @name trigger_audience_estimation
POST {{host}}/audiences/segments/{{audienceId}}/estimate
{{authHeader}}
###


# @name trigger_audience_estimation_callback
POST {{host}}/audiences/segments/{{audienceId}}/estimate/callback
{{authHeader}}

{
  "result": {
    "size": 9132
  }
}

###


# @name create_product_segment
POST {{host}}/products/segments/
{{authHeader}}

{
  "name": "demo_product_segment",
  "isTesting": false,
  "filters": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "type": "group",
    "level": 1,
    "conjunction": "and",
    "rules": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "type": "rule",
        "field": "department",
        "operator": "in",
        "value": ["KIDS", "MW"]
      },
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "type": "rule",
        "field": "category",
        "operator": "in",
        "value": ["Accessories"]
      }
    ]
  }
}
###

@productId = {{create_product_segment.response.body.id}}

# @name get_product_segment
GET {{host}}/products/segments/{{productId}}
{{authHeader}}
###


# @name trigger_product_estimation
POST {{host}}/products/segments/{{productId}}/estimate
{{authHeader}}
###


# @name trigger_product_estimation_callback
POST {{host}}/products/segments/{{productId}}/estimate/callback
{{authHeader}}

{
  "result": {
    "size": 9132
  }
}

###


# @name create_campaign
POST {{host}}/campaigns/
{{authHeader}}

{
  "name": "demo_campaign",
  "type": "Small Campaigns"
}
###
@campaignId = {{create_campaign.response.body.id}}


# @name create_version
POST {{host}}/versions/
{{authHeader}}

{
  "name": "demo_version",
  "type": "Control",
  "scheduleAt": "{{$timestamp 1 m}}",
  "campaignId": "{{campaignId}}",
  "audienceSegmentIds": ["{{audienceId}}"],
  "productSegmentIds": ["{{productId}}"]
}
###


# @name update_version
PUT {{host}}/versions/{{create_version.response.body.id}}
{{authHeader}}

{
  "scheduleAt": "{{$timestamp 30 s}}"
}
###


# @name get_campaign
GET {{host}}/campaigns/{{campaignId}}
{{authHeader}}
###


# @name campaign_launch
POST {{host}}/campaigns/{{campaignId}}/launch
{{authHeader}}
###


# @name campaign_launch_callback
POST {{host}}/campaigns/{{campaignId}}/launch/callback
{{authHeader}}
###
