openapi: 3.0.3
info:
  title: Elsie Serverless Functions - OpenAPI 3.0


  version: 1.0.
servers:
  - url: http://localhost:7071/api

tags:
  - name: upload clienteling list
    description: upload clienteling list to the elsie server 

paths:
  
  /upload-clienteling-list:
    post:
      tags:
        - upload clienteling list
      summary: receive xlsx, convert to csv, send it to elsie server
      description: ''
      operationId: uploadFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary

      
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                
  /elsie:
    post:
      tags:
        - upload clienteling list
      summary: a mock endpoint of Elsie Server
      description: save the csv file in the local server (always return 200 for the upload xlsx endpoint)
      operationId: receiveCSV
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        
        '200':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  
  schemas:
    
    ApiResponse:
      type: object
      properties:
        message:
          type: string
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
