service: upload-clienteling-list

frameworkVersion: '3'

provider:
  name: azure
  runtime: nodejs14
  region: East Asia
  os: linux
  stage: ${opt:stage}
  environment:
    STAGE: ${opt:stage}
  resourceGroup: elsie-serverless-functions

plugins:
  - serverless-azure-functions
  - serverless-webpack

package:
  exclude:
    - local.settings.json
    - .vscode/**
    - .env.*

functions:  
  upload-clienteling-list:
    name: ${opt:stage}-upload-clienteling-list
    handler: src/uploader/uploadController.uploadController
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out
  
  elsie:
    name: ${opt:stage}-elsie
    handler: src/elsie/receiveCSVController.receiveCSVController
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out
