version: "3.3"
services:
  backend:
    environment:
      STAGE: development
      SERVER_PORT: 3000
    build:
      context: .
      dockerfile: ./Dockerfile.local
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
