from typing import Literal, TypeAlias

ProductDepartment = TypeAlias = Literal[
    "COS",
    "HL",
    "JWY",
    "KIDS",
    "LSA",
    "MSA",
    "MW",
    "OTHERS",
    "WW",
]

ProductSubdepartment = TypeAlias = Literal[
    "3rd Party Consignment",
    "Accessories",
    "Bags",
    "Bath & Body",
    "Bath & Towels",
    "Bed Linens",
    "Books & Stationery",
    "Bottoms",
    "Boy's Accessories",
    "Boy's Shoes",
    "Boy's Wear",
    "Dental Care",
    "Dresses",
    "Essentials",
    "Food, Gourmet & Flowers",
    "Fragrance",
    "Furniture",
    "Girl's Wear",
    "Hair",
    "Health & Wellness",
    "Home Appliances",
    "Home Decoration",
    "Home Fragrance & Spa",
    "Jackets",
    "Kids",
    "Kitchen & Dining",
    "Knitwear",
    "Lighting",
    "Lingerie",
    "Loose Stones",
    "Luxury Storage",
    "Makeup",
    "Men's Fine Jewellery",
    "Men's Grooming",
    "Men's Shoes",
    "Mother & Baby",
    "Nail",
    "Non-Merchandise",
    "Outerwear",
    "Pets",
    "Phones",
    "Rugs",
    "Services",
    "Shoes",
    "Skincare",
    "Special Projects",
    "Suits",
    "Swimwear",
    "Tech & Gadgets",
    "Topman",
    "Tops",
    "Topshop",
    "Toys & Entertainment",
    "Travel",
    "Watches",
    "Women's Bags",
    "Women's Fine Jewellery",
    "Women's Shoes",
]

ProductCategory: TypeAlias = Literal[
    "3rd Party Consignment",
    "ACCESSORIES",
    "Accessories",
    "Accessory Sets",
    "Active",
    "Alcohol",
    "Amenities",
    "BAGS",
    "BLOUSES",
    "BRANDS",
    "Bags",
    "Bangles & Cuffs",
    "Bath & Body",
    "Bath & Body Sets",
    "Beauty Gadget",
    "Bed Accessories",
    "Bedding",
    "Beds",
    "Belts",
    "Beverage",
    "Blazers",
    "Blouses",
    "Body Moisturiser",
    "Body Treatment",
    "Books",
    "Boots",
    "Bottoms",
    "Boy's Accessories",
    "Boy's Shoes",
    "Bracelets",
    "Bras",
    "Broochs & Pins",
    "Brushes & Applicators",
    "CAS JACKETS",
    "CASUAL SHIRTS",
    "CASUAL TROUSERS",
    "COSMETICS",
    "Capes",
    "Cardigans",
    "Casual blazers",
    "Chairs",
    "Charms",
    "Cleanser",
    "Coats",
    "Collars",
    "Compression",
    "Consultation",
    "Cookware",
    "Crew Necks",
    "Cufflinks",
    "Cutlery",
    "DCK CONC",
    "DENIM",
    "DRESSES",
    "Decorative Accessories",
    "Denim",
    "Devices",
    "Diamond",
    "Dinnerware",
    "Dresses",
    "Drinkware",
    "Drones",
    "Earrings",
    "Emerald",
    "Espadrilles",
    "Evening",
    "Eye",
    "Eye Care",
    "Eyewear",
    "Face",
    "Face & Neck Mask",
    "Fashion",
    "Festive Ornaments",
    "Festive Table Top",
    "Fitness",
    "Flats",
    "Floor",
    "Flowers",
    "Food",
    "Food, Gourmet & Flowers",
    "Fragrance Sets",
    "Games & Entertainment",
    "Gilets & Vests",
    "Gloves",
    "Gowns",
    "HANGING SHOE",
    "HOSIERY",
    "Hair",
    "Hair Accessories",
    "Hair Brushes",
    "Hair Care",
    "Hair Removal",
    "Hair Styling Product",
    "Hair Styling Tools",
    "Hair Treatment",
    "Hampers",
    "Hand Care",
    "Hats",
    "Heels",
    "Home Furnishings",
    "Indoor",
    "Ingestibles",
    "JACKETS CASUAL",
    "JACKETS SMART",
    "JEANS",
    "JERSEY",
    "Jackets",
    "Jadeite",
    "Jewellery",
    "Jewellery Boxes",
    "Jumpers",
    "Jumpsuits",
    "KNITWEAR",
    "Kitchen Accessories",
    "Knitwear",
    "LLG",
    "Lighters & Cigar Accessories",
    "Linens",
    "Lip",
    "Lip Care",
    "Long Boots",
    "Luggage",
    "Makeup",
    "Makeup Accessories",
    "Makeup Sets",
    "Mattresses",
    "Men's Shoes",
    "Men's Watches",
    "Moisturiser",
    "Monk Straps",
    "Mother & Baby",
    "Nail Polish",
    "Nail Polish Remover",
    "Nail Sets",
    "Necklaces",
    "Non-Merchandise",
    "Others",
    "Outdoor",
    "Outerwear",
    "PETITES",
    "Panty",
    "Pendants",
    "Perfume",
    "Pets Accessories",
    "Polos",
    "Repair",
    "Rings",
    "Room Fragrances",
    "S/S LEISURE",
    "SHOES",
    "SHORTS",
    "SKTS SFT/CAS",
    "SLG",
    "SMART",
    "SMART COATS",
    "SMART SHIRTS",
    "SUITS",
    "SUNGLASSES",
    "SWIMWEAR",
    "Safes",
    "Sandals",
    "Scarves",
    "Services",
    "Shampoo & Conditioner",
    "Shaving",
    "Shawls",
    "Shirts",
    "Shoes",
    "Short Boots",
    "Shorts",
    "Skincare",
    "Skincare Accessories",
    "Skincare Sets",
    "Skirts",
    "Slip-Ons",
    "Small Accessories",
    "Small Appliances",
    "Socks",
    "Sofas & Seating",
    "Soft Furnishings",
    "Sound",
    "Spare Parts",
    "Stationery",
    "Storage & Shelving",
    "Suit Separates",
    "Suits",
    "Sun Care & Tanning",
    "Sunglasses",
    "Suspenders",
    "Sweatshirts",
    "Swim",
    "T-Shirts",
    "TRS/SKTS SMART",
    "TS DESIGN",
    "TS DRESS UP",
    "TS PARKWOOD",
    "Table & Serveware",
    "Tables",
    "Tabletop Accessories & Textiles",
    "Tea & Coffee",
    "Tech & Gadgets",
    "Tech Accessories",
    "Tiaras",
    "Ties",
    "Toner",
    "Toothbrush",
    "Toothpaste",
    "Tops",
    "Towels",
    "Toys",
    "Travel Accessories",
    "Trousers",
    "Trunks",
    "Turtlenecks",
    "UNDERWEAR",
    "UNDERWEAR/SOCKS",
    "Underwear",
    "V-Necks",
    "Vests",
    "Vision",
    "Wallets & Accessories",
    "Watch Winders & Boxes",
    "Watches",
    "Wedges",
    "Wellbeing",
    "Women's Watches",
    "Women's jewellery",
    "Women's watches",
    "Zip & Button Necks",
    "lace-Ups",
]

ProductSubcategory: TypeAlias = Literal[
    "$100 SUIT JKT",
    "$25 ESSENTIALS",
    "$30 SLIM",
    "1 Piece",
    "1: PU",
    "2 Piece - Bottom",
    "2 Piece - Set",
    "2: Basic Bombers",
    "3: Lightweight",
    "3: Throw-On",
    "3rd Party Consignment",
    "4: Short Puffers",
    "6: Stand Out",
    "A-Line",
    "ADIDAS ORGINAL",
    "AND FINALLY",
    "Accessories",
    "Active",
    "Air Purifiers",
    "Amenities",
    "Ankle",
    "Anoraks",
    "Anti-Aging Gadget",
    "Art & Collectibles",
    "Asian Dining",
    "Auto-Create by WE Process",
    "Auto-Create by WE Process (999)",
    "Auto-Create by WE Process (ARC)",
    "Auto-Create by WE Process (ASP)",
    "Auto-Create by WE Process (BBA)",
    "Auto-Create by WE Process (BJE)",
    "Auto-Create by WE Process (WO1)",
    "Auto-Create by WE Process (WORK)",
    "Aviator",
    "BAND OF GYPSIES",
    "BASEBALL/BOMBERS 2 (BASE)",
    "BASIC CAMI 1",
    "BASIC JERSEY 1",
    "BOILED WOOL (BDWL)",
    "BORG DENIM",
    "BRALETS CASUAL 8",
    "BRANDS",
    "Backpacks",
    "Bags",
    "Ballerinas",
    "Balm",
    "Barware",
    "Bath Soaks & Bubble Bath",
    "Bed Sets",
    "Bed Spreads",
    "Beds",
    "Beer & Cider",
    "Belts",
    "Berets",
    "Bermuda",
    "Big Kids Boys",
    "Big Kids Girls",
    "Biker",
    "Bikes",
    "Billfold Wallets",
    "Blankets",
    "Blazers",
    "Blocks & Buildings",
    "Blouson",
    "Board Shorts",
    "Boat Shoes",
    "Bodies",
    "Body Cleanser",
    "Body Exfoliator",
    "Body Moisturiser",
    "Bodycon",
    "Bodysuits",
    "Books",
    "Bootcut",
    "Boots",
    "Bottom Sheets",
    "Bottoms",
    "Bouquets",
    "Bow Ties",
    "Bowls",
    "Boxerbriefs",
    "Boxers",
    "Boy's Accessories",
    "Boy's Shoes",
    "Bracelets",
    "Briefs",
    "Brogue",
    "Broochs & Pins",
    "Brow Tools & Tweezers",
    "Brush & Applicator Cleaner",
    "Bucket Bags",
    "Butter",
    "Button",
    "CABLES",
    "CAPS AND FABRIC HEADWEAR",
    "CAS WOV PLAYSUITS",
    "CASUAL BODIES 8",
    "CASUAL BODY 2",
    "CASUAL JACKETS 4",
    "CASUAL SKIRTS 2",
    "CASUAL TRS 2",
    "CATEYE",
    "CLOTH (CLTH)",
    "CLUBMASTER",
    "COLOUR JAMIE 2",
    "COLOUR SHORT 1",
    "CONTRAST & STRIPE TEES",
    "CORE 2 FORS",
    "CORE CREWS & VEES",
    "CORE OTHER",
    "CORE ROLLS",
    "CORE TEXTURE",
    "CROP",
    "CROP WIDE 1",
    "CROPPED 4",
    "Cabinets & Sideboards",
    "Cake Stands & Domes",
    "Camisoles",
    "Capes",
    "Cardholders",
    "Cardigans",
    "Cargo",
    "Carpets",
    "Casual",
    "Champagne",
    "Check-In Luggage",
    "Chelsea",
    "Chest of Drawers",
    "Chewables",
    "Chocolates",
    "Chopping Boards",
    "Chronograph",
    "Clay",
    "Cleanser",
    "Cleansing Oil",
    "Closed Toe",
    "Clutches",
    "Coats",
    "Coffee",
    "Coin Purses",
    "Cold Weather",
    "Collars",
    "Collars & Leashes",
    "Combo",
    "Computer Accessories",
    "Computers",
    "Condiments",
    "Consultation",
    "Cooking Appliances",
    "Cosmetic Pouches",
    "Cotton & Modal",
    "Crackers",
    "Cream",
    "Crossbody",
    "Cufflinks",
    "Cufflinks (CUFF)",
    "Curler",
    "Cushions",
    "Cutlery",
    "D Frame",
    "D'Orsay",
    "DAY TO NIGHT",
    "DENIM DRESSES",
    "DENIM JACKETS",
    "DENIM SHORTS",
    "DENIM SKIRTS",
    "DEPT SPARE",
    "DESIGN VESTS",
    "DISTRIB. PIPPA (ABB)",
    "DRESSES 5",
    "DUMP (ZZZ)",
    "Daybeds",
    "Daywear Slips 2",
    "Decanters",
    "Decorative Pillows",
    "Denim",
    "Deodorant & Antiperspirant",
    "Derby",
    "Desk Accessories",
    "Diamond",
    "Diaries & Notebooks",
    "Dining",
    "Dinner Jacket",
    "Document Cases",
    "Dolly",
    "Double Breasted",
    "Dress Shirts",
    "Dresses",
    "Drones",
    "Drop Crotch",
    "Dryer",
    "Duffle Bags",
    "Duffle Coats",
    "Duvet Sets",
    "Duvets",
    "EMBEL CASUAL 8",
    "EMBELLISHED 9",
    "Earrings",
    "Emerald",
    "Empire",
    "Envelopes",
    "Espadrilles",
    "Evening",
    "Exfoliator",
    "Eye Care",
    "Eye Primer",
    "Eyebrow",
    "Eyelash Enhancer",
    "Eyeliner",
    "Eyeshadow",
    "FACE HIGHLIGHTERS",
    "FASH JSY JOGGERS",
    "FASH OUTERWEAR 3",
    "FASHION CAMI 2 HS",
    "FASHION DENIM",
    "FASHION DRESSES 4",
    "FASHION FITS 3",
    "FASHION JACKETS 3",
    "FASHION ROUNDS",
    "FASHION RUNNER",
    "FASHION SHORT 1",
    "FASHION SKINNY",
    "FASHION SOCKS",
    "FG Mid Top 1",
    "FG Sleeveless",
    "FLARE 3",
    "FORM FASHION",
    "FORM PREMIUM",
    "FORM STRETCH",
    "FORMAL TRS 2",
    "Face Towels",
    "Face Wash",
    "Fans",
    "Fashion",
    "Felt",
    "Figurines",
    "Fine stone",
    "Flared",
    "Flat Sandals",
    "Flats",
    "Flip Flops",
    "Floor",
    "Food Bowls",
    "Footbeds",
    "Formal",
    "Foundation",
    "Fresh Food",
    "Full Zip",
    "Fur",
    "G/O PLAIN 4",
    "GLITTER SOCKS",
    "GLOVES",
    "GO BODYCONS",
    "GO Heeled Sandals 2",
    "GO JERSEY G/O",
    "GO LACE GOING OUT",
    "GOING OUT SHORTS",
    "Gadgets",
    "Gel",
    "Gilets",
    "Gilets & Vests",
    "Gin",
    "Gloves",
    "Gold",
    "HEELED SHOES 5",
    "HIGH RISE SHORT 1",
    "Hair",
    "Hair Accessories",
    "Hair Removal",
    "Hair Removal Gadget",
    "Hair Styling Product",
    "Hair Treatment",
    "Hampers",
    "Hand Cleanser",
    "Hand Moisturiser",
    "Hand Towels",
    "Hats",
    "Headphones",
    "Heeled",
    "Heeled Sandals",
    "Heels",
    "Henley",
    "High Shoes 1",
    "High Top",
    "Highlighter",
    "Holdalls",
    "Honey",
    "Hoodies",
    "Hot Chocolate",
    "Humidors",
    "INTERNATIONAL 7",
    "Infant Boys",
    "Invitations & Cards",
    "JERSEY DRESSES 3",
    "JOGGERS",
    "JUMPSUITS 2",
    "Jackets",
    "Jade",
    "Jadeite",
    "Jeans",
    "Jeggings",
    "Jersey Emb/Trim 1",
    "Jersey Print 1",
    "Jersey Tops",
    "Jewellery Boxes",
    "Jogger",
    "Jumpsuits",
    "KNITWEAR 1",
    "Key Holders",
    "Kids",
    "Knife",
    "Knit",
    "L/S CHECK SHIRTS 1",
    "L/S SMART PRINT 2",
    "LG: Basic Leggings",
    "LG: Fashion Leggings",
    "LIPS LIPSTICK",
    "LOW RISE SHORT 1",
    "LS BASICS",
    "LS BODY 6",
    "LS CHECKS",
    "LS CORE CREW",
    "LS CROP 6",
    "LS DESIGN",
    "LS FORM PLAINS",
    "LS PLAINS",
    "LS STRIPES",
    "LS SWEATS 7",
    "LTD EDITION",
    "LW BOMBERS (BMR)",
    "LW OUTERWEAR",
    "LW SHORT JACKETS",
    "Laptop Bags",
    "Leather",
    "Leather & Shearling",
    "Leather Separates",
    "Leggings",
    "Lifestyle",
    "Lighters",
    "Lighting",
    "Lip",
    "Lip Gloss",
    "Lip Liner",
    "Lip Plumper",
    "Lip Tint",
    "Lip Treatment",
    "Liquids",
    "Loafers",
    "Long Sleeves",
    "Long/Continental Wallets",
    "Loose Tea",
    "Lotion",
    "Lounge",
    "Low Top",
    "MAXI&MIDI C/UPS",
    "MEDIUM BELTS",
    "METAL FASHION",
    "MID JERSEY",
    "MID RISE SHORT 1",
    "MIDI PLAIN",
    "MIDI PRINT",
    "MUSCLE (&SLIM)SUITS",
    "MW Roll Top 1",
    "Makeup Accessories",
    "Makeup Remover",
    "Manual",
    "Mask",
    "Mats",
    "Mattresses",
    "Men's Shoes",
    "Mermaid",
    "Messenger Bags",
    "Mid Calf",
    "Milk Jugs",
    "Mist",
    "Moisturiser",
    "Monk Straps",
    "Mother & Baby",
    "Mousse",
    "Mules",
    "Multi Gem",
    "NA (CPOP)",
    "NA (DESN)",
    "NAILS GEL",
    "NON SKINNY COLOUR",
    "NOVELTY SOCKS",
    "Nail Polish",
    "Nail Polish Remover",
    "Napkins",
    "Natural Bristles",
    "Nature",
    "Necklaces",
    "Non-Merchandise",
    "Not In Use (DES)",
    "ONE PIECES",
    "OTHER BAGS",
    "OUTERWEAR",
    "OUTERWEAR 3",
    "OVERSHIRTS",
    "OXFORD CIRCUS 5",
    "OXFORD CIRCUS 6",
    "Objects",
    "Office",
    "Oil",
    "Open Toe",
    "Optical",
    "Others",
    "Oval",
    "Over The Knee",
    "Over the knee",
    "Oxford",
    "P JONI 1",
    "P MOM 1",
    "P SIDNEY 1",
    "P STRAIGHT 1",
    "PACK SOCKS",
    "PARKAS & MACS",
    "PATTERN",
    "PLAIN CASUAL 8",
    "PLAIN DAY TOPS 2",
    "PLAIN FASHION",
    "PLAIN SWIMS",
    "PLAIN VEST",
    "PLASTIC AVIATOR",
    "PLAYSUITS",
    "PLAYSUITS/DUNGAREES 5",
    "PLN & TRIM SOCKS",
    "PLN SOCKS",
    "PREMIUM",
    "PREMIUM 3",
    "PREMIUM SMART 7",
    "PRINT",
    "PRINT 9-9 TOPS 1",
    "PRINT BARDOT 5",
    "PRINT CASUAL 8",
    "PRINT DAY TOPS 2",
    "PRINTED PLAST",
    "PROG SHIRTS 2 (BLOP)",
    "PUFFERS",
    "PVC",
    "Padded",
    "Pants",
    "Patterned Cdi 4",
    "Patterned Top 2",
    "Pearl",
    "Pens & Pencils",
    "Peplum",
    "Performance",
    "Personalization & Customization",
    "Phone Cases",
    "Pillows",
    "Pills",
    "Placecard Holders",
    "Plates",
    "Platters",
    "Pointed Toe",
    "Port",
    "Pots & Pans",
    "Pouches",
    "Powder",
    "Premium 6",
    "Printed Slips 2",
    "Puffer",
    "Push-Up",
    "READERS",
    "RUCKSACKS",
    "Rain",
    "Rectangle",
    "Red Wine",
    "Religion",
    "Repair",
    "Rings",
    "Roll On",
    "Room Fragrances",
    "Round Toe",
    "Ruby",
    "Rum",
    "S/S PLAIN SHIRTS 2",
    "S/S PRINT SHIRTS 2",
    "SANDALS 4",
    "SHOES",
    "SHORT WVN PLN",
    "SHORTS",
    "SHORTS 2",
    "SKINNY SUIT JKT",
    "SKIRTS 4",
    "SL TANK 3",
    "SL TOPS",
    "SLEEVELESS 2",
    "SMART BACKPACK",
    "SMART BRALETS 9",
    "SMART HEADWEAR",
    "SMART JERSEY 1",
    "SMART PLAIN 9",
    "SMART TUNICS 9",
    "SMART XBODY",
    "SOFT BLAZERS",
    "SOFT SKIRTS 2",
    "SPORT SOCKS",
    "SPORTS",
    "SS BASIC TEE 4",
    "SS CHECKS",
    "SS CROP TEE 4 HS",
    "SS FORM DESIGN",
    "SS LONG TEE 4",
    "SS PRINT JERSEY",
    "SS TOPS",
    "STRETCH SKINNIES",
    "STRETCH SLIM",
    "STRIPE CASUAL 8",
    "STRUCTURED BLAZER",
    "SUNTOP PRINT 5",
    "SWING (WWW)",
    "Safes",
    "Sandals",
    "Sapphire",
    "Satchels",
    "Saucers",
    "Scarves",
    "Seasonal Project",
    "Serum",
    "Services",
    "Serving Knife",
    "Serving Set",
    "Set: Pad Triangle",
    "Set: Padd Bralet",
    "Sets",
    "Setting Spray",
    "Shampoo",
    "Shampoo & Conditioner",
    "Shams",
    "Shaving Cream",
    "Shaving Oil",
    "Shaving Tool",
    "Shawls & Blankets",
    "Sheath",
    "Sheet Mask",
    "Shift",
    "Shirts & Blouses",
    "Shoe Care",
    "Shoes",
    "Short Boots",
    "Short Sleeves",
    "Shorts",
    "Shoulder Bags",
    "Side",
    "Silk & Chiffon",
    "Silver",
    "Single Breasted",
    "Skates",
    "Skincare Accessories",
    "Skinny",
    "Skirt",
    "Skirts",
    "Skort",
    "Skorts",
    "Sleepwear",
    "Sleeveless",
    "Slides",
    "Slim",
    "Sling Backs",
    "Small Accessories",
    "Smart Tech",
    "Smart Trackers",
    "Smoking Slippers",
    "Sneakers",
    "Sng: Mini",
    "Socks",
    "Sofas",
    "Soft",
    "Soft Accessories",
    "Solid",
    "Sound Accessories",
    "Spoon",
    "Sports bras",
    "Spray",
    "Square Toe",
    "Stools",
    "Straight",
    "Straightner",
    "Strapless",
    "Straw",
    "Stripe Top 2",
    "Styling Product",
    "Suiting",
    "Sunglasses",
    "Suspenders",
    "Sweatpants",
    "Sweets",
    "T-Shirts",
    "TEE & CAKE",
    "TG: PU & Suedette",
    "TOPMAN UW",
    "TRIAL",
    "TROPHY JACKETS",
    "TUBE SOCKS",
    "TV Accessories",
    "Table & Serveware",
    "Table Games",
    "Tablecloths & Runners",
    "Tables",
    "Tablet Accessories",
    "Tablet Cases",
    "Tailored",
    "Tall",
    "Tank Tops",
    "Tapered",
    "Tea & Coffee",
    "Tea Spoon",
    "Tea Strainers",
    "Teapots",
    "Technology",
    "Televisions",
    "Tequila & Mezcal",
    "Thick (>30Mm)",
    "Thongs",
    "Three Piece",
    "Ties",
    "Tinted Moisturiser",
    "Toasters & Kettles",
    "Toddler Boys",
    "Toddler Girls",
    "Toner",
    "Toothpaste",
    "Top Sheets",
    "Tops",
    "Tote Bags",
    "Tourbillon",
    "Towels",
    "Toys",
    "Track",
    "Travel Accessories",
    "Travel Sets",
    "Travel Wallets",
    "Treatment",
    "Trench",
    "Trousers",
    "Trunks",
    "Tumblers",
    "Umbrellas",
    "Under Eye Concealer",
    "V-Necks",
    "VEE (VEE)",
    "VOLUME SUIT TRS",
    "Varsity",
    "Vests",
    "Vintage",
    "Vision Accessories",
    "Vodka",
    "W/BRKER SHLL JKTS",
    "W:BASICS (AAA)",
    "WADED/LINED BOMBERS",
    "WE OWN THE NIGHT",
    "WIDE 1",
    "WINTER HATS",
    "WJ:Seperates",
    "WOOL MID 2",
    "WOOL UNSTRUCTURED 2",
    "WOV PLAIN",
    "WT: Mensy & Utility",
    "WT: Mensy Trousers",
    "Waistbags",
    "Wallets",
    "Wallpaper",
    "Wash Bags",
    "Watch Accessories",
    "Watch Winders",
    "Watches",
    "Weather Boot",
    "Weekenders",
    "Whisky",
    "White Wine",
    "Windbreaker",
    "Wine",
    "Women's Bags",
    "Woven Maxis 2",
    "Woven Tops",
    "Wrap",
    "Wreath",
    "Wvn Smrt Uns (WUNS)",
    "Wvn Smrt Unstruct 2",
    "XMAS",
    "Zip Around Wallets",
    "beanies",
    "lace-Ups",
]

ProductBrandGroup: TypeAlias = Literal[
    "ASH",
    "Accessories (LSA)",
    "Accessories (MSA)",
    "Accessories (OPW)",
    "Apple & Samsung  (LIF)",
    "Art & Experience (LIF)",
    "Artistry Makeup (COS)",
    "Athleisure (LSA)",
    "Athleisure (MSA)",
    "Athleisure (MW)",
    "Athleisure (WW)",
    "Bags (OPW)",
    "Bathroom & Spa (LIF)",
    "Beauty Accessories (COS)",
    "Charlotte Olympia",
    "Classic Shoes (MSA)",
    "Classics (WW)",
    "Concession (JBO)",
    "Contemporary (MW)",
    "Contemporary (WW)",
    "Contemporary Bags (LSA)",
    "Contemporary Bags (MSA)",
    "Contemporary Collections (MW)",
    "Contemporary Collections (WW)",
    "Contemporary Shoes (LSA)",
    "Core Skincare (COS)",
    "DUMMY",
    "Designer (LIF)",
    "Designer Bags (LSA)",
    "Designer Bags (MSA)",
    "Designer Collections (MW)",
    "Designer Collections (WW)",
    "Designer Jewellery (JBO)",
    "Designer Scents (COS)",
    "Designer Shoes (LSA)",
    "Designer Shoes (MSA)",
    "Established",
    "Expressive",
    "Food, Gourmet & Flowers (LIF)",
    "Fur (LSA)",
    "Fur (WW)",
    "Furnishing (MW)",
    "Furniture, Lighting & Furnishings (LIF)",
    "Generic Jewellery (JBO)",
    "Gianvito Rossi",
    "Hair, Body & Nail (COS)",
    "Home Decoration, Occasions & Stationery (LIF)",
    "International Brands (JBO)",
    "Jade (JBO)",
    "Kids (LIF)",
    "Kids (LSA)",
    "Kids (WW)",
    "Kiosk (LSA)",
    "Kitchen & Dining (LIF)",
    "Lab 3rd Party Consignment",
    "Lifestyle & Scent",
    "Lifestyle Scents (COS)",
    "Lifestyle Skincare (COS)",
    "Lingerie (WW)",
    "Luxury Collections (MW)",
    "Luxury Collections (WW)",
    "Luxury Storage (LIF)",
    "MTM/MTO (MW)",
    "Men's Grooming (COS)",
    "Modern",
    "Next Generation (MW)",
    "Next Generation (OPM)",
    "Next Generation (WW)",
    "Pedder Red",
    "Pets (LIF)",
    "Resort (MW)",
    "Resort (WW)",
    "Shoes (OPW)",
    "Stuart Weitzman",
    "Tailoring (MW)",
    "Tech, Entertainment & Gadgets (LIF)",
    "Topshop/Topman",
    "Towels & Linens (LIF)",
    "Travel & Luggage (LIF)",
    "Vintage (LSA)",
    "Vintage (MSA)",
    "Vintage Antique Jewellery (JBO)",
    "Watches (JBO)",
    "Watches (LSA)",
    "Watches (MSA)",
    "Wellbeing (COS)",
    "Women'Shoes",
]
