import Head from 'next/head'
import { useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { Inter } from 'next/font/google'

import '../../i18n'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => page)
  const { i18n } = useTranslation()

  useEffect(() => {
    if (typeof window === 'undefined') {
      return
    }
    const language = sessionStorage.getItem('i18nextLng')
    if (!language) {
      return
    }
    i18n.changeLanguage('language')
  }, [])

  return (
    <>
      <Head>
        <title>Elsie Admin Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={inter.className}>
        {getLayout(<Component {...pageProps} />, pageProps)}
      </main>
    </>
  )
}
