service: update-staff-ids-mapping

configValidationMode: off

frameworkVersion: "3"

provider:
  name: azure
  location: East Asia
  runtime: nodejs14
  stage: ${opt:stage, 'production'}
  resourceGroup: lc-tech-elsie
  os: linux  
  environment:
    STAGE: "${opt:stage, self:provider.stage}"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceInclude:
        - knex
        - mysql2
    packager: "yarn"

functions:
  create-user:
    handler: src/createUser/controller.createUserController
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out

  update-staff-customer:
    handler: src/updateStaff/controller.updateStaffCustomerController
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out
  
  update-manager:
    handler: src/updateManager/controller.updateManagerController
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out

  update-storemanager:
    handler: src/updateStoremanager/controller.updateStoreManagerController
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out
  
  update-supervisor:
    handler: src/updateSupervisor/controller.updateSupervisorController
    events:
      - http: true
        methods:
          - POST
        authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out

  healthcheck:
    handler: src/healthCheck/controller.healthcheckController
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out

plugins:
  - serverless-azure-functions
  - serverless-webpack
